import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useEffect, useState } from "react";
import { ActivityIndicator, Image, ImageBackground, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { getApiBaseUrl } from "@/constants/oauth";
import { useBusiness } from "@/lib/business-context";
import * as Auth from "@/lib/_core/auth";
import { resolveMediaUrl } from "@/lib/media";

const BANNER = "/manus-storage/business-ivoire-marketplace-banner_0b19a6cb.png";
const LOGO = "/manus-storage/business-ivoire-3d-logo_de8f6d54.png";

export function AuthGate({ children, accessOnly = false }: { children: React.ReactNode; accessOnly?: boolean }) {
  const { authenticated, authLoading, retryAuth } = useBusiness();
  const [showWelcome, setShowWelcome] = useState(!accessOnly);
  const [mode, setMode] = useState<"signup" | "signin">("signup");
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState<string>(); const [busy, setBusy] = useState(false);
  useEffect(() => { if (accessOnly) return; const timer = setTimeout(() => setShowWelcome(false), 1450); return () => clearTimeout(timer); }, [accessOnly]);
  if (showWelcome) return <ScreenContainer edges={["top", "bottom", "left", "right"]} style={styles.welcome}><View style={styles.welcomeMark}><Image source={{ uri: resolveMediaUrl(LOGO) }} style={styles.welcomeLogo} /></View><Text style={styles.welcomeBrand}>BUSINESS IVOIRE</Text><Text style={styles.welcomeTitle}>Bienvenue sur{`\n`}Business Ivoire</Text><Text style={styles.welcomeText}>Achetez. Vendez. Grandissez.</Text><ActivityIndicator color="#D5A72C" size="small" style={styles.welcomeSpinner} /></ScreenContainer>;
  if (authLoading) return <ScreenContainer style={styles.loading}><ActivityIndicator color="#D5A72C" size="large" /><Text style={styles.loadingText}>Ouverture de votre espace…</Text></ScreenContainer>;
  if (authenticated || !accessOnly) return <>{children}</>;
  const submit = async () => {
    try {
      setBusy(true); setMessage(undefined);
      const response = await fetch(`${getApiBaseUrl()}/api/auth/local/${mode === "signup" ? "signup" : "signin"}`, { method: "POST", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ name, email, password }) });
      const result = await response.json();
      if (!response.ok) throw new Error(result.error || "Connexion indisponible.");
      if (result.app_session_id) await Auth.setSessionToken(result.app_session_id);
      if (result.user) await Auth.setUserInfo({ ...result.user, lastSignedIn: new Date(result.user.lastSignedIn) });
      await retryAuth();
    } catch (error) { setMessage(error instanceof Error ? error.message : "Connexion indisponible."); } finally { setBusy(false); }
  };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} style={styles.screen}><ImageBackground source={{ uri: resolveMediaUrl(BANNER) }} imageStyle={styles.backgroundImage} style={styles.hero}><View style={styles.content}><View style={styles.mark}><MaterialIcons name="business-center" size={30} color="#FFFFFF" /></View><Text style={styles.eyebrow}>BUSINESS IVOIRE</Text><Text style={styles.title}>Votre marché commence ici.</Text><Text style={styles.text}>Créez votre compte gratuitement. Aucun navigateur externe, aucune redirection compliquée.</Text><View style={styles.form}><View style={styles.switcher}><TouchableOpacity onPress={() => setMode("signup")} style={[styles.switch, mode === "signup" && styles.switchActive]}><Text style={[styles.switchText, mode === "signup" && styles.switchTextActive]}>Créer un compte</Text></TouchableOpacity><TouchableOpacity onPress={() => setMode("signin")} style={[styles.switch, mode === "signin" && styles.switchActive]}><Text style={[styles.switchText, mode === "signin" && styles.switchTextActive]}>Se connecter</Text></TouchableOpacity></View>{mode === "signup" ? <TextInput value={name} onChangeText={setName} placeholder="Votre nom ou activité" placeholderTextColor="#8D9B8E" style={styles.input} /> : null}<TextInput value={email} onChangeText={setEmail} placeholder="Adresse e-mail" autoCapitalize="none" keyboardType="email-address" placeholderTextColor="#8D9B8E" style={styles.input} /><TextInput value={password} onChangeText={setPassword} placeholder="Mot de passe (10 caractères min.)" secureTextEntry placeholderTextColor="#8D9B8E" style={styles.input} />{message ? <Text style={styles.error}>{message}</Text> : null}<TouchableOpacity disabled={busy} style={[styles.button, busy && styles.disabled]} onPress={() => void submit()}><Text style={styles.buttonText}>{busy ? "Veuillez patienter…" : mode === "signup" ? "Créer mon compte gratuit" : "Accéder à mon compte"}</Text><MaterialIcons name="arrow-forward" size={18} color="#102015" /></TouchableOpacity></View></View></ImageBackground></ScreenContainer>;
}
const styles = StyleSheet.create({ welcome: { alignItems: "center", backgroundColor: "#07150B", justifyContent: "center", padding: 24 }, welcomeMark: { alignItems: "center", backgroundColor: "#173D24", borderColor: "#D5A72C", borderRadius: 28, borderWidth: 1, height: 64, justifyContent: "center", overflow: "hidden", width: 64 }, welcomeLogo: { height: 58, width: 58 }, welcomeBrand: { color: "#D5A72C", fontSize: 11, fontWeight: "900", letterSpacing: 2, marginTop: 20 }, welcomeTitle: { color: "#FFFFFF", fontSize: 31, fontWeight: "900", lineHeight: 37, marginTop: 10, textAlign: "center" }, welcomeText: { color: "#C9D5C9", fontSize: 14, fontWeight: "700", marginTop: 10 }, welcomeSpinner: { marginTop: 30 }, screen: { backgroundColor: "#07150B", padding: 16 }, hero: { borderRadius: 26, flex: 1, overflow: "hidden" }, backgroundImage: { opacity: 0.34 }, content: { backgroundColor: "rgba(7,21,11,0.74)", flex: 1, justifyContent: "center", padding: 20 }, mark: { alignItems: "center", backgroundColor: "#176B35", borderColor: "#D5A72C", borderRadius: 22, borderWidth: 1, height: 48, justifyContent: "center", width: 48 }, eyebrow: { color: "#D5A72C", fontSize: 11, fontWeight: "900", letterSpacing: 1.7, marginTop: 16 }, title: { color: "#FFFFFF", fontSize: 30, fontWeight: "900", letterSpacing: -0.7, lineHeight: 35, marginTop: 7 }, text: { color: "#DCE7DB", fontSize: 13, lineHeight: 19, marginTop: 8 }, form: { backgroundColor: "#F7F4EA", borderRadius: 18, gap: 9, marginTop: 22, padding: 12 }, switcher: { backgroundColor: "#E5E2D4", borderRadius: 11, flexDirection: "row", padding: 3 }, switch: { alignItems: "center", borderRadius: 9, flex: 1, paddingVertical: 9 }, switchActive: { backgroundColor: "#176B35" }, switchText: { color: "#536158", fontSize: 11, fontWeight: "900" }, switchTextActive: { color: "#FFFFFF" }, input: { backgroundColor: "#FFFFFF", borderColor: "#DDD9CA", borderRadius: 11, borderWidth: 1, color: "#102015", fontSize: 13, minHeight: 45, paddingHorizontal: 11 }, error: { color: "#A1342C", fontSize: 12, lineHeight: 16 }, button: { alignItems: "center", backgroundColor: "#D5A72C", borderRadius: 12, flexDirection: "row", gap: 7, justifyContent: "center", minHeight: 48 }, disabled: { opacity: 0.65 }, buttonText: { color: "#102015", fontSize: 13, fontWeight: "900" }, loading: { alignItems: "center", backgroundColor: "#07150B", justifyContent: "center" }, loadingText: { color: "#DCE7DB", fontSize: 14, fontWeight: "700", marginTop: 12 } });
