import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useWindowDimensions, Alert, FlatList, Image, StyleSheet, Text, TouchableOpacity, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { useBusiness } from "@/lib/business-context";
import { formatFcfa } from "@/lib/marketplace";
import { resolveMediaUrl } from "@/lib/media";
import { trpc } from "@/lib/trpc";

export default function ListingDetail() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { width } = useWindowDimensions(); const { authenticated, currentUserId } = useBusiness();
  const listing = trpc.marketplace.publicById.useQuery({ id: Number(id) });
  const favorite = trpc.marketplace.toggleFavorite.useMutation({ onSuccess: () => void listing.refetch() });
  const conversation = trpc.conversations.createDirect.useMutation({ onSuccess: (item) => router.push(`/conversation/${item.id}` as never) });
  if (!listing.data) return <ScreenContainer style={s.loading}><Text style={s.loadingText}>{listing.isLoading ? "Chargement de l’annonce…" : "Annonce introuvable"}</Text></ScreenContainer>;
  const item = listing.data; const isOwnListing = Boolean(item.seller && item.seller.userId === currentUserId); const sellerVerified = item.seller?.identityStatus === "selfie_captured";
  const openAccess = () => router.push("/access" as never);
  const contactSeller = () => { if (!authenticated) return openAccess(); if (isOwnListing) return Alert.alert("Votre annonce", "Vous ne pouvez pas vous écrire à vous-même."); if (item.seller) void conversation.mutateAsync({ userId: item.seller.userId }); };
  return <ScreenContainer style={s.screen}><FlatList data={item.images} horizontal pagingEnabled keyExtractor={(image) => String(image.id)} renderItem={({ item: image }) => <Image source={{ uri: resolveMediaUrl(image.url) }} style={[s.image, { width }]} />} ListEmptyComponent={<View style={[s.emptyImage, { width }]}><MaterialIcons name="photo-library" size={42} color="#D5A72C" /></View>} ListFooterComponent={<View style={s.body}><View style={s.row}><Text style={s.category}>{item.category}</Text><TouchableOpacity onPress={() => authenticated ? void favorite.mutateAsync({ listingId: item.id }) : openAccess()}><MaterialIcons name="favorite-border" size={25} color="#176B35" /></TouchableOpacity></View><Text style={s.title}>{item.title}</Text><Text style={s.price}>{formatFcfa(item.price)}</Text><Text style={s.meta}>{item.location} · {item.condition === "new" ? "Neuf" : item.condition === "service" ? "Service" : "Occasion"}</Text><Text style={s.description}>{item.description}</Text>{item.seller ? <View style={s.sellerCard}><View style={s.sellerAvatar}><Text style={s.sellerInitial}>{item.seller.displayName.slice(0, 1).toUpperCase()}</Text></View><View style={s.sellerInfo}><Text style={s.sellerLabel}>Vendeur</Text><Text style={s.sellerName}>{item.seller.displayName}</Text><View style={[s.verification, sellerVerified ? s.verificationOk : s.verificationPending]}><MaterialIcons name={sellerVerified ? "verified" : "info-outline"} size={14} color={sellerVerified ? "#176B35" : "#9A6811"} /><Text style={[s.verificationText, sellerVerified ? s.verificationTextOk : s.verificationTextPending]}>{sellerVerified ? "Identité vérifiée par selfie" : "Identité en cours de vérification"}</Text></View></View></View> : <View style={s.sellerUnavailable}><Text style={s.sellerUnavailableText}>Profil vendeur indisponible</Text></View>}<TouchableOpacity disabled={!item.seller || conversation.isPending} onPress={contactSeller} style={[s.contact, (!item.seller || conversation.isPending) && s.disabled]}><MaterialIcons name="chat-bubble-outline" size={19} color="#102015" /><Text style={s.contactText}>{isOwnListing ? "Votre annonce" : conversation.isPending ? "Ouverture…" : "Écrire au vendeur"}</Text></TouchableOpacity></View>} /></ScreenContainer>;
}
const s = StyleSheet.create({ screen:{backgroundColor:"#F7F4EA"}, loading:{alignItems:"center",backgroundColor:"#F7F4EA",justifyContent:"center"},loadingText:{color:"#647067"}, image:{height:290},emptyImage:{alignItems:"center",backgroundColor:"#173D24",height:290,justifyContent:"center"},body:{padding:18},row:{alignItems:"center",flexDirection:"row",justifyContent:"space-between"},category:{color:"#176B35",fontSize:12,fontWeight:"900"},title:{color:"#102015",fontSize:25,fontWeight:"900",marginTop:10},price:{color:"#176B35",fontSize:22,fontWeight:"900",marginTop:10},meta:{color:"#647067",fontSize:13,marginTop:6},description:{color:"#344238",fontSize:15,lineHeight:22,marginTop:20},sellerCard:{alignItems:"center",backgroundColor:"#FFFFFF",borderColor:"#E2DED2",borderRadius:15,borderWidth:1,flexDirection:"row",gap:12,marginTop:22,padding:13},sellerAvatar:{alignItems:"center",backgroundColor:"#173D24",borderRadius:22,height:44,justifyContent:"center",width:44},sellerInitial:{color:"#F5D875",fontSize:17,fontWeight:"900"},sellerInfo:{flex:1},sellerLabel:{color:"#68756C",fontSize:10,fontWeight:"800",textTransform:"uppercase"},sellerName:{color:"#102015",fontSize:15,fontWeight:"900",marginTop:1},verification:{alignItems:"center",alignSelf:"flex-start",borderRadius:999,flexDirection:"row",gap:4,marginTop:6,paddingHorizontal:7,paddingVertical:4},verificationOk:{backgroundColor:"#E9F5EC"},verificationPending:{backgroundColor:"#FFF3D9"},verificationText:{fontSize:10,fontWeight:"900"},verificationTextOk:{color:"#176B35"},verificationTextPending:{color:"#9A6811"},sellerUnavailable:{backgroundColor:"#FFF3D9",borderRadius:12,marginTop:22,padding:12},sellerUnavailableText:{color:"#9A6811",fontSize:12,fontWeight:"800"},contact:{alignItems:"center",backgroundColor:"#D5A72C",borderRadius:14,flexDirection:"row",gap:8,justifyContent:"center",marginTop:18,paddingVertical:15},disabled:{opacity:.58},contactText:{color:"#102015",fontSize:15,fontWeight:"900"} });
