import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useMemo, useState } from "react";
import { ActivityIndicator, FlatList, Image, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";

import { Card } from "@/components/business-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useBusiness } from "@/lib/business-context";
import { formatFcfa } from "@/lib/marketplace";
import { resolveMediaUrl } from "@/lib/media";
import { trpc } from "@/lib/trpc";

const categories = ["Tout", "Véhicules", "Immobilier", "Électronique", "Emploi & services", "Agriculture", "Maison & loisirs", "Mode & beauté", "Autres"];

export default function DiscoverScreen() {
  const [search, setSearch] = useState(""); const [category, setCategory] = useState("Tout"); const { authenticated } = useBusiness();
  const listings = trpc.marketplace.publicList.useInfiniteQuery({ limit: 20 }, { getNextPageParam: (lastPage) => lastPage.nextCursor ?? undefined, refetchOnMount: "always", refetchOnReconnect: true });
  const utils = trpc.useUtils();
  const toggleFavorite = trpc.marketplace.toggleFavorite.useMutation({ onSuccess: () => void utils.marketplace.publicList.invalidate() });
  const data = useMemo(() => (listings.data?.pages.flatMap((page) => page.items) ?? []).filter((item) => (category === "Tout" || item.category === category) && `${item.title} ${item.description} ${item.location}`.toLowerCase().includes(search.toLowerCase())), [listings.data, category, search]);
  const next = () => { if (listings.hasNextPage && !listings.isFetchingNextPage) void listings.fetchNextPage(); };
  const requireAccess = () => router.push("/access" as never);
  return <ScreenContainer style={styles.screen}><FlatList data={data} keyExtractor={(item) => String(item.id)} refreshing={listings.isFetching && !listings.isFetchingNextPage} onRefresh={() => void listings.refetch()} onEndReached={next} onEndReachedThreshold={0.55} contentContainerStyle={styles.content} ListHeaderComponent={<><Text style={styles.title}>Explorer les annonces</Text><View style={styles.search}><MaterialIcons name="search" size={20} color="#647067" /><TextInput value={search} onChangeText={setSearch} placeholder="Rechercher un produit, service ou lieu" placeholderTextColor="#7A858F" style={styles.searchInput} /></View><FlatList horizontal data={categories} keyExtractor={(item) => item} contentContainerStyle={styles.chips} showsHorizontalScrollIndicator={false} renderItem={({ item }) => <TouchableOpacity onPress={() => setCategory(item)} style={[styles.chip, category === item && styles.chipActive]}><Text style={[styles.chipText, category === item && styles.chipTextActive]}>{item}</Text></TouchableOpacity>} /></>} renderItem={({ item }) => <TouchableOpacity activeOpacity={0.82} onPress={() => router.push(`/listing/${item.id}` as never)}><Card style={styles.card}>{item.images[0] ? <Image source={{ uri: resolveMediaUrl(item.images[0].url) }} style={styles.image} /> : <View style={styles.imageFallback}><MaterialIcons name="photo-library" size={32} color="#D5A72C" /></View>}<View style={styles.cardBody}><Text numberOfLines={2} style={styles.cardTitle}>{item.title}</Text><Text style={styles.price}>{formatFcfa(item.price)}</Text><Text style={styles.meta}>{item.category} · {item.location}</Text><View style={styles.actions}><TouchableOpacity onPress={() => authenticated ? void toggleFavorite.mutateAsync({ listingId: item.id }) : requireAccess()} style={styles.action}><MaterialIcons name="favorite-border" size={19} color="#176B35" /><Text style={styles.actionText}>Favori</Text></TouchableOpacity><TouchableOpacity onPress={() => authenticated ? router.push(`/listing/${item.id}` as never) : requireAccess()} style={styles.action}><MaterialIcons name="chat-bubble-outline" size={18} color="#176B35" /><Text style={styles.actionText}>Écrire</Text></TouchableOpacity></View></View></Card></TouchableOpacity>} ListFooterComponent={listings.isFetchingNextPage ? <ActivityIndicator color="#176B35" style={styles.footerLoader} /> : null} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name={listings.isError ? "cloud-off" : "search-off"} size={34} color="#D5A72C" /><Text style={styles.emptyTitle}>{listings.isError ? "Chargement indisponible" : "Aucune annonce trouvée"}</Text><Text style={styles.emptyText}>{listings.isError ? "Vérifiez votre connexion puis relancez le chargement." : "Modifiez vos critères ou publiez la première annonce."}</Text>{listings.isError ? <TouchableOpacity onPress={() => void listings.refetch()} style={styles.retry}><Text style={styles.retryText}>Réessayer</Text></TouchableOpacity> : null}</View>} /></ScreenContainer>;
}
const styles = StyleSheet.create({ screen: { backgroundColor: "#F7F4EA" }, content: { gap: 12, padding: 14, paddingBottom: 28 }, title: { color: "#102015", fontSize: 26, fontWeight: "900", marginBottom: 13 }, search: { alignItems: "center", backgroundColor: "#FFF", borderColor: "#DEDCCF", borderRadius: 15, borderWidth: 1, flexDirection: "row", gap: 8, paddingHorizontal: 12 }, searchInput: { color: "#102015", flex: 1, minHeight: 48 }, chips: { gap: 8, paddingVertical: 14 }, chip: { backgroundColor: "#FFF", borderColor: "#DEDCCF", borderRadius: 999, borderWidth: 1, paddingHorizontal: 13, paddingVertical: 8 }, chipActive: { backgroundColor: "#176B35", borderColor: "#176B35" }, chipText: { color: "#36513B", fontSize: 12, fontWeight: "800" }, chipTextActive: { color: "#FFF" }, card: { overflow: "hidden" }, image: { height: 170, width: "100%" }, imageFallback: { alignItems: "center", backgroundColor: "#173D24", height: 170, justifyContent: "center" }, cardBody: { padding: 13 }, cardTitle: { color: "#102015", fontSize: 16, fontWeight: "900" }, price: { color: "#176B35", fontSize: 17, fontWeight: "900", marginTop: 7 }, meta: { color: "#647067", fontSize: 12, marginTop: 5 }, actions: { flexDirection: "row", gap: 10, marginTop: 12 }, action: { alignItems: "center", backgroundColor: "#EDF5EB", borderRadius: 9, flexDirection: "row", gap: 5, paddingHorizontal: 10, paddingVertical: 8 }, actionText: { color: "#176B35", fontSize: 12, fontWeight: "900" }, empty: { alignItems: "center", gap: 7, padding: 30 }, emptyTitle: { color: "#102015", fontSize: 16, fontWeight: "900" }, emptyText: { color: "#647067", fontSize: 12, textAlign: "center" }, retry: { backgroundColor: "#176B35", borderRadius: 10, marginTop: 8, paddingHorizontal: 14, paddingVertical: 10 }, retryText: { color: "#FFFFFF", fontWeight: "900" }, footerLoader: { marginVertical: 12 } });
